#+Macro: fname Mattia
#+Macro: lname Bunel
#+Macro: me {{{fname}}} {{{lname}}}
#+Macro: halid mattia-bunel

#+OPTIONS: html-style:nil html5-fancy:t html-style-include-scripts:nil 
#+OPTIONS: title:t toc:nil num:nil html-postamble:nil
#+HTML_DOCTYPE: xhtml5

#+AUTHOR: {{{me}}}
#+TITLE: {{{me}}}
#+DESCRIPTION: LASTIG {{{me}}}'s homepage

#+HTML_HEAD: <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
#+HTML_HEAD: <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
#+HTML_HEAD: <link href="../static/css/all.css" rel="stylesheet">
#+HTML_HEAD: <link href="../static/css/mystyle.css" rel="stylesheet">
#+HTML_HEAD: <script src="../static/js/hal.js" charset="utf-8"></script>
#+HTML_HEAD: <link rel=meta type="application/rdf+xml" title="FOAF" href="../static/foaf.rdf">

#+BEGIN_translation
[[file:index_fr.org][Version française]]
#+END_translation

#+BEGIN_presentation
I'm a Phd Candidate inside of the [[http://choucas.ign.fr/][Choucas]] project. The aim of this
project is "[…] to provide methods and tools for enriching,
structuring, querying and visualising spatial data coming from
heterogeneous sources and reasoning to help the rescue teams to speed
up the phase of victims location and to better estimate a probable
location area."

My PhD specifically focuses on the question of transforming a position
described in an set of coordinates, computationally exploitable. To do
this, we must work with the imprecision of natural language and the
semantic variability of spatial prepositions.

#+END_presentation

#+BEGIN_team
I'm a member of the LASTIG's [[https://umrlastig.github.io/meig/][MEIG]] team.
#+END_team

#+BEGIN_contact
Contact links :
#+BEGIN_contactlist
- Mail @@html:<a href="mailto:mattia.bunel@ign.fr"><i class="fas
  fa-envelope"></i></a>@@ 
- My GPG key @@html:<a href="static/public-key.txt"><i class="fas
  fa-key"></i></a>@@
- Phone @@html:<a href="tel:+33143988000"><i class="fas
  fa-phone"></i></a>@@
- Twitter @@html:<a href="https://twitter.com/mattiabunel"><i
  class="fab fa-twitter"></i></a>@@
- GitHub @@html:<a href="https://github.com/MBunel"><i class="fab
  fa-github"></i></a>@@
- OCRID @@html:<a href="https://orcid.org/0000-0001-7751-3507"><i class="fas
  fa-user-tag"></i></a>@@
- FOAF @@html:<a href="static/foaf.rdf"><i class="fas
  fa-address-card"></i></a>@@
#+END_contactlist
#+END_contact

* Research Interests
- Fuzzy logic
- Vagueness
- Imprecision
- Naive Geography
- Spatial localisation
* Experience
Before my doctorate, I was an engineer in the [[http://www.parisgeo.cnrs.fr/][Géographie-cités]]
research laboratory. I mainly worded for the [[http://www.world-seastems.cnrs.fr/][WorldSeastems]] research
project. The main objective of this project is to exploit the archives
of the first marine insurer (Lloyd's of London) to study the evolution
of maritime traffic, since the nineteenth century.

* Teaching
** Mastère DESIGEO
- Vagueness modelisation introduction:

The objective of this course [[https://github.com/MBunel/Cours/blob/master/DESIGEO/ModèlesVagues/][(fr)]] is to introduce the notion of spatial
vagueness and present the different models allowing its modelization.

** Master IGAST
- Spatial analysis:

Introduction to Maup and multivariate analysis

** ENSG 2nd year
- PostgreSQL/PotGIS introduction:
Practical introduction to Postgres and postgis
- Spatial analysis introduction:
Practical introduction to some morphology indicators

** ENSG 1st year
- QGIS introduction:
Practical introduction to GIS using QGIS

# * Encadrement
* Publications

#+BEGIN_notaBene
This list is an automatic extraction of my [[https://hal.archives-ouvertes.fr/][Hal]] profile. There may be
some extraction errors.
#+END_notaBene

** Articles
#+BEGIN_export html
<ol id="pubJ" class="sub"></ol>
#+END_export
** Conferences
#+BEGIN_export html
<ol id="pubC" class="sub"></ol>
#+END_export
** Books
#+BEGIN_export html
<ol id="pubB" class="sub"></ol>
#+END_export
** Posters
#+BEGIN_export html
<ol id="pubW" class="sub"></ol>
#+END_export
** Others
#+BEGIN_export html
<ol id="pubO" class="sub"></ol>
#+END_export
#+BEGIN_EXPORT html
<script type="text/javascript">
window.onload = function() {
    var me = 'mattia-bunel';
    getJournalPublicationsAuthor(me);
    getConfPublicationsAuthor(me);
    getBookPublicationsAuthor(me);
    getWorkshopPublicationsAuthor(me);
    getOtherPublicationsAuthor(me);
    //getInvitedTalksAuthor(me);
};
</script>
#+END_EXPORT
* Science popularization
- I was on a radio show [[https://www.radiocampusparis.org/insitu15-la-high-tech-au-service-des-secours-en-montagne-2-19/#embed][(fr)]] about mountain rescue and my research work.
- I have also participated in a popular science program on twitter [[https://twitter.com/EnDirectDuLabo/status/1092344316578676736][(fr)]].
